global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # 도커에서 외부 호스트 접근시

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']